export type StandardFontName = 'Courier' | 'Helvetica' | 'TimesRoman' | 'Symbol' | 'ZapfDingbats';

export interface StandardFontFamilyDefinition {
  readonly id: string;
  readonly label: string;
  readonly cssFamily: string;
  readonly pdfName: StandardFontName;
}

export const STANDARD_FONT_FAMILIES: readonly StandardFontFamilyDefinition[] = [
  {
    id: 'helvetica',
    label: 'Helvetica',
    cssFamily: 'Helvetica, Arial, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'times-new-roman',
    label: 'Times New Roman',
    cssFamily: '"Times New Roman", Times, serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'arial',
    label: 'Arial',
    cssFamily: 'Arial, Helvetica, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'arial-narrow',
    label: 'Arial Narrow',
    cssFamily: '"Arial Narrow", Arial, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'avenir-next',
    label: 'Avenir Next',
    cssFamily: '"Avenir Next", Avenir, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'calibri',
    label: 'Calibri',
    cssFamily: 'Calibri, "Gill Sans", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'candara',
    label: 'Candara',
    cssFamily: 'Candara, Calibri, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'corbel',
    label: 'Corbel',
    cssFamily: 'Corbel, "Trebuchet MS", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'futura',
    label: 'Futura',
    cssFamily: 'Futura, "Century Gothic", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'gill-sans',
    label: 'Gill Sans',
    cssFamily: '"Gill Sans", "Gill Sans MT", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'lato',
    label: 'Lato',
    cssFamily: '"Lato", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'montserrat',
    label: 'Montserrat',
    cssFamily: '"Montserrat", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'noto-sans',
    label: 'Noto Sans',
    cssFamily: '"Noto Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'open-sans',
    label: 'Open Sans',
    cssFamily: '"Open Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'pt-sans',
    label: 'PT Sans',
    cssFamily: '"PT Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'roboto',
    label: 'Roboto',
    cssFamily: 'Roboto, "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'segoe-ui',
    label: 'Segoe UI',
    cssFamily: '"Segoe UI", Tahoma, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'source-sans-pro',
    label: 'Source Sans Pro',
    cssFamily: '"Source Sans Pro", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'ubuntu',
    label: 'Ubuntu',
    cssFamily: 'Ubuntu, "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'verdana',
    label: 'Verdana',
    cssFamily: 'Verdana, Geneva, sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'cambria',
    label: 'Cambria',
    cssFamily: 'Cambria, "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'garamond',
    label: 'Garamond',
    cssFamily: 'Garamond, "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'georgia',
    label: 'Georgia',
    cssFamily: 'Georgia, "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'palatino',
    label: 'Palatino',
    cssFamily: '"Palatino Linotype", Palatino, serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'baskerville',
    label: 'Baskerville',
    cssFamily: '"Baskerville", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'bookman',
    label: 'Bookman Old Style',
    cssFamily: '"Bookman Old Style", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'charter',
    label: 'Charter',
    cssFamily: 'Charter, "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'noto-serif',
    label: 'Noto Serif',
    cssFamily: '"Noto Serif", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'courier',
    label: 'Courier',
    cssFamily: 'Courier, "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'inconsolata',
    label: 'Inconsolata',
    cssFamily: '"Inconsolata", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'menlo',
    label: 'Menlo',
    cssFamily: 'Menlo, Monaco, monospace',
    pdfName: 'Courier',
  },
  {
    id: 'roboto-mono',
    label: 'Roboto Mono',
    cssFamily: '"Roboto Mono", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'source-code-pro',
    label: 'Source Code Pro',
    cssFamily: '"Source Code Pro", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'fira-code',
    label: 'Fira Code',
    cssFamily: '"Fira Code", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'space-mono',
    label: 'Space Mono',
    cssFamily: '"Space Mono", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'poppins',
    label: 'Poppins',
    cssFamily: '"Poppins", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'inter',
    label: 'Inter',
    cssFamily: '"Inter", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'nunito',
    label: 'Nunito',
    cssFamily: '"Nunito", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'manrope',
    label: 'Manrope',
    cssFamily: '"Manrope", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'jetbrains-mono',
    label: 'JetBrains Mono',
    cssFamily: '"JetBrains Mono", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'playfair-display',
    label: 'Playfair Display',
    cssFamily: '"Playfair Display", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'merriweather',
    label: 'Merriweather',
    cssFamily: '"Merriweather", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'source-serif-4',
    label: 'Source Serif 4',
    cssFamily: '"Source Serif 4", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'raleway',
    label: 'Raleway',
    cssFamily: '"Raleway", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'oswald',
    label: 'Oswald',
    cssFamily: '"Oswald", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'work-sans',
    label: 'Work Sans',
    cssFamily: '"Work Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'dm-sans',
    label: 'DM Sans',
    cssFamily: '"DM Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'dm-serif-display',
    label: 'DM Serif Display',
    cssFamily: '"DM Serif Display", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'noto-sans-jp',
    label: 'Noto Sans JP',
    cssFamily: '"Noto Sans JP", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'noto-serif-display',
    label: 'Noto Serif Display',
    cssFamily: '"Noto Serif Display", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'cabin',
    label: 'Cabin',
    cssFamily: '"Cabin", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'karla',
    label: 'Karla',
    cssFamily: '"Karla", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'space-grotesk',
    label: 'Space Grotesk',
    cssFamily: '"Space Grotesk", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'sora',
    label: 'Sora',
    cssFamily: '"Sora", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'bitter',
    label: 'Bitter',
    cssFamily: '"Bitter", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'archivo',
    label: 'Archivo',
    cssFamily: '"Archivo", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'heebo',
    label: 'Heebo',
    cssFamily: '"Heebo", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'crimson-pro',
    label: 'Crimson Pro',
    cssFamily: '"Crimson Pro", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'ibm-plex-sans',
    label: 'IBM Plex Sans',
    cssFamily: '"IBM Plex Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'ibm-plex-serif',
    label: 'IBM Plex Serif',
    cssFamily: '"IBM Plex Serif", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
  {
    id: 'ibm-plex-mono',
    label: 'IBM Plex Mono',
    cssFamily: '"IBM Plex Mono", "Courier New", monospace',
    pdfName: 'Courier',
  },
  {
    id: 'urbanist',
    label: 'Urbanist',
    cssFamily: '"Urbanist", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'sofia-sans',
    label: 'Sofia Sans',
    cssFamily: '"Sofia Sans", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'asap',
    label: 'Asap',
    cssFamily: '"Asap", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'quicksand',
    label: 'Quicksand',
    cssFamily: '"Quicksand", "Helvetica Neue", sans-serif',
    pdfName: 'Helvetica',
  },
  {
    id: 'zilla-slab',
    label: 'Zilla Slab',
    cssFamily: '"Zilla Slab", "Times New Roman", serif',
    pdfName: 'TimesRoman',
  },
];
