name: CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Run unit build
        run: npm run build

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22.12.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install --no-audit --no-fund
      - name: Build application
        run: npm run build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          PLAYWRIGHT_TEST_PORT: 4400
        run: npx playwright test
