name: CI

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        env:
          CHROME_BIN: /usr/bin/google-chrome
